404.adoc, _config/site.yml, _layouts/base.html.slim, docs/index.adoc, stylesheets/styles.scss
=> Switching slack links to gitter

docs/python/remote-guide.adoc
Fixed path for Installation guide link for a broken link
=> Update to path for Installation Guide link

docs/secure-quickstart.adoc
First draft of secure quickstart.
=> First draft of secure quickstart

docs/training/example-2.adoc, docs/training/example-3.adoc, docs/training/example-4.adoc, docs/training/example-5.adoc, docs/training/training-101.adoc, docs/training/ui-orientation.adoc
Still can't figure out why I am having this issue. So now images are on the website but the webpages are pointing to the wrong directory.
Correct:
https://beer-garden.io/docs/training/images/complex-beer-statistics-fields.png
Whats Loaded:
https://beer-garden.io/docs/training/training-101/images/complex-beer-statistics-fields.png
=> Changed to more direct path instead of relative path

docs/training/example-2.adoc, docs/training/example-3.adoc, docs/training/example-4.adoc, docs/training/example-5.adoc, docs/training/ui-orientation.adoc
Another random change before I make these absolute links.
=> Changing images to use double colons instead of single

docs/training/example-2.adoc, docs/training/example-3.adoc, docs/training/example-4.adoc, docs/training/example-5.adoc, docs/training/ui-orientation.adoc
Follow an example for nested imaged directories. Still trying to figure out why we are having problems with displaying images.
=> Following example for nested image directories

docs/training/training-101.adoc
Fixed the installation guide link on the training 101 doc
=> Fixed link for install guide

docs/training/example-2.adoc, docs/training/example-4.adoc
Had to fix an example and wanted to test a variable for links.
=> More edits

docs/training/example-2.adoc, docs/training/example-3.adoc, docs/training/example-4.adoc, docs/training/example-5.adoc, docs/training/training-101.adoc
Hopefully the last edits on the training page.
=> Fixed Backup Link

docs/python/_includes/type.adoc, docs/training/ui-orientation.adoc
=> Adding file trigger and file parameter information

.github/workflows/deploy.yml
=> Adding new Github Action Script

.github/workflows/deploy.yml
Trying out the Cache Action for the bundle files
Example:
https://github.com/actions/cache/blob/main/examples.md#ruby---bundler
=> Adding Caching for Ruby

.github/workflows/deploy.yml
=> Rolling Back Changes

docs/app/configuration.adoc
=> Fixing link for config yaml

_config/site.yml, docs/app/github-actions.adoc, docs/index.adoc, index.adoc
This page will help explain what is going on in our triggers
=> Adding page on Github Actions

docs/app/github-actions.adoc, docs/index.adoc
=> Fixing Anchors

_layouts/base.html.slim
This fixes #77 for the development and github profiles. ~Going to put this in draft until I can verify that it doesn't break the gitlab profile.~ Seems to work.
=> Forcing nav links to point at landing page

.gitlab-ci.yml, _ext/pipeline.rb, _layouts/base.html.slim, stylesheets/styles.scss
This improves the Gitlab CI build
=> Layout updates for gitlab build

docs/plugins/python/_includes/beer-conf.adoc, docs/plugins/python/_includes/hello-world-client.adoc, docs/plugins/python/_includes/hello-world-local-entry-point.adoc, docs/plugins/python/_includes/hello-world-remote-entry-point.adoc, docs/plugins/python/local-guide.adoc, docs/plugins/python/remote-guide.adoc, docs/startup/installation-guides/rhel.adoc
Update plugin docs so that they at least should work with current brewtils.
=> Update plugin creation docs

docs/app/parent-child.adoc
Closes #89 
Added documentation for the `CommandPublishingBlocklist`.
=> Added documentation for command blocklist
